// File: models/commissionRecordModel.js
// Description: A channel-partner commission accrual for one booking, one CP.
//   Generated by services/commissionService.js when a CP-attributed Sale is
//   created or its attribution is edited.

import mongoose from 'mongoose';

const payoutSchema = new mongoose.Schema(
  {
    label: { type: String, required: true },
    amount: { type: Number, required: true, min: 0 },
    trigger: {
      type: String,
      enum: ['on_booking', 'on_agreement', 'on_registration', 'on_possession'],
      default: 'on_booking',
    },
    status: { type: String, enum: ['pending', 'paid'], default: 'pending' },
    dueOn: { type: Date, default: null },
    paidOn: { type: Date, default: null },
    paidBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  },
  { _id: false }
);

const historyEntrySchema = new mongoose.Schema(
  {
    at: { type: Date, default: Date.now },
    by: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    action: { type: String },
    note: { type: String },
  },
  { _id: false }
);

const commissionRecordSchema = new mongoose.Schema(
  {
    organization: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Organization',
      required: true,
      index: true,
    },
    sale: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Sale',
      required: true,
      index: true,
    },
    channelPartner: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'ChannelPartner',
      required: true,
      index: true,
    },
    agent: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'ChannelPartnerAgent',
      default: null,
    },
    commissionRule: { type: mongoose.Schema.Types.ObjectId, ref: 'CommissionRule', default: null },
    sharePct: { type: Number, default: 100, min: 0, max: 100 },
    grossAmount: { type: Number, default: 0, min: 0 },
    tdsAmount: { type: Number, default: 0, min: 0 },
    netAmount: { type: Number, default: 0, min: 0 },
    payouts: [payoutSchema],
    status: {
      type: String,
      enum: ['accrued', 'partially_paid', 'paid', 'cancelled'],
      default: 'accrued',
      index: true,
    },
    history: [historyEntrySchema],
  },
  { timestamps: true }
);

commissionRecordSchema.index({ organization: 1, status: 1 });
commissionRecordSchema.index({ organization: 1, channelPartner: 1 });
// One commission record per (booking, channel partner) — guards the
// read-then-write in syncCommissionForSale against a concurrent-call race.
commissionRecordSchema.index({ sale: 1, channelPartner: 1 }, { unique: true });

// Keep `status` in sync with the payout states (unless cancelled).
commissionRecordSchema.methods.recomputeStatus = function () {
  if (this.status === 'cancelled') return;
  const payouts = this.payouts || [];
  const paid = payouts.filter((p) => p.status === 'paid').length;
  if (payouts.length > 0 && paid === payouts.length) this.status = 'paid';
  else if (paid > 0) this.status = 'partially_paid';
  else this.status = 'accrued';
};

const CommissionRecord = mongoose.model('CommissionRecord', commissionRecordSchema);

export default CommissionRecord;
